name: Alternative Azure Deployment Test

on:
  workflow_dispatch:  # Manual trigger only for now

jobs:
  deploy_alternative:
    runs-on: ubuntu-latest
    name: Alternative Azure Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install and Build
        run: |
          npm install
          npm run build
          
      - name: Deploy to Azure Static Web Apps (Alternative Config)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_WATER_01EB75C0F }}
          action: 'upload'
          app_location: '/'
          output_location: 'dist'
          skip_build: true  # We already built it
