name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      # - main  # TODO: UNCOMMENT BEFORE PULL REQUEST
      - deploymentTroubleshooting
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      # - main  # TODO: UNCOMMENT BEFORE PULL REQUEST
      - deploymentTroubleshooting

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Debug - Environment Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Working directory: $(pwd)"
          ls -la
      - name: Debug - Check Node and NPM
        run: |
          node --version
          npm --version
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Debug - Check Build Output
        run: |
          echo "Checking dist directory:"
          ls -la dist/ || echo "dist directory not found"
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_WATER_01EB75C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_WATER_01EB75C0F }}
          action: "close"
